// Dart runtime
// https://github.com/GoogleCloudPlatform/functions-framework-dart

import { createRuntime } from './base'

export const dart = createRuntime({
  name: 'dart',
  displayName: 'Dart',
  repo: 'https://github.com/GoogleCloudPlatform/functions-framework-dart',
  quickstartUrl:
    'https://github.com/GoogleCloudPlatform/functions-framework-dart/blob/main/docs/quickstarts/01-quickstart-dart.md',
  checkCommand: 'dart',
  checkArgs: ['--version'],
  installHint: 'Install Dart from https://dart.dev or use: brew install dart',
  filePatterns: ['pubspec.yaml'],
  runCommand: ['dart', 'run', 'bin/server.dart'],
  dockerfile: `FROM dart:stable AS build
LABEL fnkit.fn="true"
WORKDIR /app
COPY pubspec.* ./
RUN dart pub get
COPY . .
RUN dart run build_runner build --delete-conflicting-outputs
RUN dart compile exe bin/server.dart -o bin/server

FROM scratch
COPY --from=build /runtime/ /
COPY --from=build /app/bin/server /app/bin/server
CMD ["/app/bin/server"]
`,
  template: (projectName: string) => {
    const safeName = projectName.replace(/-/g, '_')
    return {
      files: {
        'pubspec.yaml': `name: ${safeName}
description: A Google Cloud Function
version: 1.0.0

environment:
  sdk: ^3.0.0

dependencies:
  functions_framework: ^0.4.0
  shelf: ^1.0.0

dev_dependencies:
  build_runner: ^2.0.0
  functions_framework_builder: ^0.4.0
`,
        'lib/functions.dart': `import 'package:functions_framework/functions_framework.dart';
import 'package:shelf/shelf.dart';

@CloudFunction()
Response function(Request request) => Response.ok('Hello, World!');
`,
        'bin/server.dart': `// GENERATED CODE - DO NOT MODIFY BY HAND
// This file is generated by build_runner. Run:
//   dart run build_runner build --delete-conflicting-outputs

import 'package:functions_framework/serve.dart';
import 'package:${safeName}/functions.dart' as function_library;

Future<void> main(List<String> args) async {
  await serve(args, _nameToFunctionTarget);
}

FunctionTarget? _nameToFunctionTarget(String name) => switch (name) {
      'function' => FunctionTarget.http(
          function_library.function,
        ),
      _ => null
    };
`,
      },
      postCreate: ['dart pub get'],
    }
  },
})
